on:
  push:
    branches:
      - main
    paths:
      - "dotnet/sdk/3.1/**"
  pull_request:
    branches:
      - main
    paths:
      - "dotnet/sdk/3.1/**"
jobs:
  Release:
    uses: liatrio-cloud/github-workflows/.github/workflows/docker-build-conventional.yml@main
    with:
      directory: "dotnet/sdk/3.1"
      tagPrefix: "dotnet-sdk-3.1"
      imageName: "ghcr.io/liatrio-cloud/runner-images/dotnet-sdk-3.1"
