on:
  push:
    branches:
      - main
      - reusable-workflow
#     paths:
#       - "nodejs/12/**"
  pull_request:
    branches:
      - main
    paths:
      - "nodejs/12/**"
jobs:
  Release: # Use reusable workflow
    uses: liatrio-cloud/github-workflows/.github/workflows/docker-build-conventional.yml@docker-build
    with:
      directory: "nodejs/12" #Mono repo location
      tagPrefix: "nodejs-12"
      imageName: "ghcr.io/liatrio-cloud/runner-images/nodejs-12"
