on:
  push:
    branches:
      - main
    paths:
      - "nodejs/12/**"
  pull_request:
    branches:
      - main
    paths:
      - "nodejs/12/**"
  workflow_dispatch:

name: Node.js 12 build

jobs:
  Release: 
    uses: liatrio-enterprise/github-workflows/.github/workflows/docker-build-conventional.yml@main
    with:
      directory: "nodejs/12"
      tagPrefix: "nodejs-12"
      imageName: "ghcr.io/liatrio-enterprise/runner-images/nodejs-12"
