on:
  push:
    branches:
      - main
    paths:
      - "terraform/1.0/**"
  pull_request:
    branches:
      - main
    paths:
      - "terraform/1.0/**"
  workflow_dispatch: 

name: Terraform/Terragrunt image build

jobs:
  Release:
    uses: liatrio-enterprise/github-workflows/.github/workflows/docker-build-conventional.yml@main
    with:
      directory: "terraform/1.0"
      tagPrefix: "terraform-1.0"
      imageName: "ghcr.io/liatrio-enterprise/runner-images/terraform-1.0"
